workflows:
  android-release:
    name: Build APK Release
    max_build_duration: 60
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build Release APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - sami.fereh@gmail.com
